app:
  bookshopName: "Bookshop"
  gatewayUri: "http://localhost:8070"
  webServiceUri: "http://localhost:8080"
server:
  port: 8080
spring:
  main:
    banner-mode: off
  application:
    name: web_service

logging:
  level:
    org.springframework: "WARN"
    ru.kirius: "WARN"
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss} - %msg%n"
    file: "%d{dd-MM-yyyy HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: "./logs/webServiceLogs.log"