DROP TABLE IF EXISTS orders;
CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL
  , ordernumber BIGINT NOT NULL
  , orderdate DATE NOT NULL
  , consumername VARCHAR(75) NOT NULL
  , consumersurname VARCHAR(75) NOT NULL
  , country VARCHAR(30) NOT NULL
  , region VARCHAR(30) NOT NULL
  , city VARCHAR(30) NOT NULL
  , street VARCHAR(30) NOT NULL
  , housenumber INT NOT NULL
  , flatnumber INT NOT NULL
  , cost BIGINT NOT NULL
  , status VARCHAR(20) NOT NULL
  );

DROP TABLE IF EXISTS ordernumber;
CREATE TABLE ordernumber (
  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL
  , num INT NOT NULL
  , lastordernumber BIGINT NOT NULL
  );


