server:
  port: 8076

spring:
  application:
    name: "data_storage_service"
  main:
    banner-mode: off

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090

logging:
  level:
    org.springframework: "DEBUG"
    ru.kirius: "DEBUG"
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss} - %msg%n"
    file: "%d{dd-MM-yyyy HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: "./logs/dataStorageLogs.log"