DROP TABLE IF EXISTS digitalbooks;
CREATE TABLE digitalbooks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL
  , name VARCHAR(255) NOT NULL
  , authorname VARCHAR(75) NOT NULL
  , authorsurname VARCHAR(75) NOT NULL
  , description VARCHAR(1000)
  , bookcoverurl VARCHAR(75) NOT NULL
  , pdfbookurl VARCHAR(75) NOT NULL
  , fb2bookurl VARCHAR(75) NOT NULL
  , price BIGINT NOT NULL
  );

DROP TABLE IF EXISTS paperbooks;
CREATE TABLE paperbooks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL
  , name VARCHAR(255) NOT NULL
  , authorname VARCHAR(75) NOT NULL
  , authorsurname VARCHAR(75) NOT NULL
  , description VARCHAR(1000)
  , bookcoverurl VARCHAR(75) NOT NULL
  , quantity INT NOT NULL
  , price BIGINT NOT NULL
  );


