app:
  gatewayUri: "http://127.0.0.1:8070"
  adminServiceUri: "http://127.0.0.1:8085"


server:
  port: 8085
spring:
  main:
    banner-mode: off
  application:
    name: web_service
  security:
    oauth2:
      client:
        provider:
          spring:
            issuer-uri: http://localhost:8090
        registration:
          adminService:
            provider: spring
            client-id: adminService
            client-secret: "secret"
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid,resource.read

logging:
  level:
    org.springframework: "WARN"
    ru.kirius: "WARN"
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss} - %msg%n"
    file: "%d{dd-MM-yyyy HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: "./logs/adminWebServiceLogs.log"